project_name: golines
before:
  hooks:
    - go clean -x

builds:
  - main: .
    flags:
      - -trimpath
      - -v
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - GOAMD64=v3
    ldflags:
      - -s -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser 

universal_binaries:
  - replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - files:
      - README.md
      - LICENSE
    wrap_in_directory: true

snapshot:
  name_template: "{{ incpatch .Version }}-pre+{{ .ShortCommit }}"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"

announce:
  skip: true
